### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by walterheino** [spartantri/wafme#1]
Hi there

I'm trying to get WAFme working. Now I'm confronted with following error:

root@modsec:/opt/wafme# ./WAFme.py
/opt/wafme/Reference-Manual.html
Getting Variables
Starting rule id will be : 37183
Increases to rule id will be : 10
Press CTRL+C to finish tailing audit.log and output the rules to REQUEST-903.900                   3-CUSTOMAPP-EXCLUSION-RULES.conf
Traceback (most recent call last):
  File "./WAFme.py", line 449, in <module>
    main()
  File "./WAFme.py", line 445, in main
    t.follow()
  File "/opt/wafme/tail.py", line 59, in follow
    self.callback(line)
  File "./WAFme.py", line 106, in extractor
    uri=re.search('^\w+\s(\/[^\?\s]+)\??.*\sHTTP\/(?:(?:1|2)\.?(?:1|0)?)$', find                   _values('request_line', jsonlog)[0])
  File "./WAFme.py", line 96, in find_values
    json.loads(json_repr, object_hook=_decode_dict)  # Return value ignored.
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

It happens after starting WAFme and the first modsecurity dedection is written to the modsecurity audit log

Cheers and thanks for any advise

**Comment by spartantri** [comment]
Hi @walterheino, Are you using the MoSecurity audit log json format? [SecAuditLogFormat](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecAuditLogFormat)

**Comment by walterheino** [comment]
Hi spartantri

I don't think so. It a out of the box installation of modsecurity

Here the log configuration I found:

# -- Audit log configuration -------------------------------------------------

# Log the transactions that are marked by a rule, as well as those that
# trigger a server error (determined by a 5xx or 4xx, excluding 404,
# level response status codes).
#
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"

# Log everything we know about a transaction.
SecAuditLogParts ABIJDEFHZ

# Use a single file for logging. This is much easier to look at, but
# assumes that you will use the audit log only ocassionally.
#
SecAuditLogType Serial
SecAuditLog /var/log/apache2/modsec_audit.log

# Specify the path for concurrent audit logging.
#SecAuditLogStorageDir /opt/modsecurity/var/audit/

**Comment by spartantri** [comment]
Rotate the auditlog, change the format to json with `SecAuditLogFormat JSON` and try again, the default is native but it is problematic for scripting, also you may feed the audit log straight into logstash/elasticsearch for better indexing [ModSec and ELK](https://spartantri.com/ModSecurity/?p=64).

What do you intend to do?
I wrote this tool to help configuring ModSecurity with CRS +3 to work, which can be specially annoying in high paranoia levels (PL4) and will require several iterations but lower PL will make it in a single pass depending on the application.
If you want to write rules from zero to use as stand alone or in conjunction with CRS better try using my other tool [WebAppProfiler](https://github.com/spartantri/webappprofiler).

As for the json format, you can do lot of cool stuff when using the json format from the CLI (but ELK is much better) so it doesn't look cryptic like:
```
cat  modsec_audit.log | python -m json.tool | pygmentize -g
cat  modsec_audit.log | jq ''
cat  modsec_audit.log | jq '{id: .transaction.transaction_id, req: .request.request_line, action: .audit_data.action, response: .response.status } | select(.id=="WYne2H8AAQEAAGUaFm4AAAAD")'
cat  modsec_audit.log | jq '{transaction: .transaction, request: .request, action: .audit_data.action, response: .response.status, messages: .audit_data.messages }'
cat  modsec_audit.log | jq --arg var_value "$variable_value" '.[] | select(.name==$var_value)'
```

**Comment by spartantri** [comment]
PL4 is painful especially if the wrong body processor is in use, (e.g. if you do json and the urlencoded processor is active it will fail miserably), I use a mix of both CRS PL4 with wafme tunning and a webappprofiler ruleset for securing every element and getting meaningful warnings when needed and remove the extra noise.
